BOT_TOKEN: "1677935498:AAFnSl2FXPaSZ8xlNAI2CzTGvaiQNBOj89Y"
MESSENGER_TOKEN: "EAAF5ZA8L6hnUBAJjhWUh5g0sk7ZB6Ub9yKuEzk6Ael2Ym5oX2JpTSJHT0rk9WAVGNw92ZB3pzkNMfw5PnTZA7SpVqa0fTLAwWZCQvK4I0npb1ZB9zIqZAKqRuUQheIVglOlqw4mZCP3ZApvVKxYsAymDCn1ZCK7iqsTp92CHYBGwbGZA57B14S9rgOl"
MESSENGER_TEST_TOKEN: <<token>>
MESSENGER_VERIFY_TOKEN: "bonobo"