
I like this recommendation.: "I like this"
I have already watched it.: "Seen it"
Tell me more about it.: "Tell me more"
Recommend me something else please.: "Something else"
Tell me something about it.: "More information"
I would like a similar recommendation.: "Similar"
I want to restart for a new movie.: "Restart"
I would like to quit now.: "Quit"
